from django.urls import path
from . import accountviews as views

urlpatterns = [
    path('signin/', views.signIn, name='signin'),
    path('signup/', views.signUp, name='signup'),
    path('terms/', views.terms, name='terms'),
    path('postsignin/', views.postsignin, name="postsignin"),
    path('postsignup/', views.postsignup, name="postsignup"),
    path('logout/', views.logout_new, name="logout"),
    path('sellersignin/', views.sellersignin, name='sellersignin'),
    path('sellersignup/', views.sellersignup, name='sellersignup'),
    path('sellerpostsignin/', views.sellerpostsignin, name='sellerpostsignin'),
    path('sellerpostsignup/', views.sellerpostsignup, name='sellerpostsignup'),
    path('verify/', views.verifyEmail, name="verifyEmail"),
    path('verifymymail/', views.verifymymail),
    path('forgetpassword/<str:by>/<str:stat>',
         views.forgetPassword, name="forgetpassword"),
    path('verifygst/', views.verifygst, name="verifygst"),
    path('verifybank/', views.verifybank, name="verifybank"),
    path('cancelchq/', views.cancelchq, name="cancelchq"),
    path('addproduct/', views.addproduct, name="addproduct"),
    path('sellermyproduct/<int:typep>',
         views.sellermyproduct, name="sellermyproduct"),
    path('editproduct/<str:idi>', views.sellereditproduct,
         name="sellereditproduct"),
    path('deleteFeature/<str:fid>/<str:pid>',
         views.deleteFeature, name="deleteFeature"),
    path('updateFeature/<str:fid>/<str:pid>/<str:loop>',
         views.updateFeature, name="updateFeature"),
    path('removeimg/<str:pid>/<str:imgid>', views.removeimg, name="removeimg"),
    path('updateimg/<str:pid>', views.updateimg, name="updateimg"),
    path('removeproduct/<str:pid>', views.removeproduct, name="removeproduct"),
    path('updateproduct/<str:pid>', views.updateproduct, name="updateproduct"),
    path('updateoffer/<str:pid>/<str:oid>',
         views.updateoffer, name="updateoffer"),
    path('updatefeature/<str:pid>/', views.updatefeature, name="updatefeature"),
    path('sellerdashboard/', views.sellerdashboard, name="dashboard"),
    path('sellerprofile/', views.sellerprofile, name="sellerprofile"),
    path('sellereditprofile/', views.sellereditprofile, name="sellereditprofile"),
    path('sellerorder/<int:ord>', views.sellerorder, name="sellerorder"),
    path('sellertransaction/<int:cred>',
         views.sellertransaction, name="sellertransaction"),
    path('subscriptionplan/', views.subscriptionplan, name="subscriptionplan"),
    path('getsubscription/<str:plan>',
         views.getsubscription, name="getsubscription"),
    path('subscribed/', views.subscribed, name="subscribed"),
    path('contactus/', views.contactus, name="contactus"),
    path('help/', views.help, name="help"),
    path('reporttrans/', views.reporttrans, name="reporttrans")

    # path('first/',views.firstTimeLogin,name="firstlogin")
]
